FROM postgres:15 as builder
RUN apt update && apt install -y git build-essential postgresql-server-dev-15
RUN git clone --branch v0.4.2 https://github.com/pgvector/pgvector.git
RUN cd pgvector && make && make install

FROM postgres:15
COPY --from=builder /usr/lib/postgresql/15/lib/vector.so /usr/lib/postgresql/15/lib/vector.so
COPY --from=builder /usr/share/postgresql/15/extension /usr/share/postgresql/15/extension
COPY --from=builder /usr/lib/postgresql/15/lib/bitcode /usr/lib/postgresql/15/lib/bitcode